name: Main workflow
on: push
jobs:
  build:
    name: Elixir action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: docker-compose up -d
    - run: docker-compose exec -T cd src && mix test